### ISSUE TITLE
Usecase?

### ISSUE THREAD

**Issue by dzid26** [arthurrichards77/iterative-learning-control#4]
I looked at the ILC implementation and I noticed that you are essentially remembering error over time for the preprogrammed sequence. 
But for any new different input, the learnt error would be immediately wrong. 

Seems like it can only work for repetitive tasks. :)

**Comment by arthurrichards77** [comment]
You're spot-on - it's the nature of ILC that it requires the task to be repetitive.  I've added a brief introduction to the README to clarify this, including a quote from a survey paper #5 

We tried to deploy it for "drone dancing" but with limited success - it worked to a point, shaping the input to improve the reference tracking despite hard-to-measure delays and dynamics, but the disturbances limited performance and it will never achieve perfect tracking.

I still think it's a great method for other types of robots though.
